const rooms={campus:'assets/campus.png',classroom:'assets/classroom.png',library:'assets/library.png',laboratory:'assets/laboratory.png',computer_lab:'assets/computer_lab.png',cafeteria:'assets/cafeteria.png',bedroom:'assets/bedroom.png',creators_room:'assets/creators_room.png'};
const labels={campus:'Campus',classroom:'Sala de aula',library:'Biblioteca',laboratory:'Laboratório',computer_lab:'Informática',cafeteria:'Cantina',bedroom:'Quarto',creators_room:'Sala dos Criadores'};
let state=JSON.parse(localStorage.getItem('eticaGameState')||'null')||{room:'campus',x:45,energy:80,knowledge:35,reputation:50,ethics:50,mission:0,done:[]};
const $=s=>document.querySelector(s), scene=$('#scene'), player=$('#player'), modal=$('#modal'), content=$('#modalContent');
const missions=[
 {title:'Missão 1 — Créditos justos',text:'Seu grupo terminou um jogo educacional. Uma colega contribuiu com roteiro, testes e acessibilidade, mas não programou. O que fazer?',choices:[['Incluir o nome e descrever a contribuição',8,3,5,'Correto: autoria e créditos devem refletir contribuições reais, não apenas programação.'],['Omitir porque ela não escreveu código',-8,-4,-6,'Problema: contribuição intelectual e de desenvolvimento pode assumir várias formas.'],['Colocar todos como “programadores”',-3,-2,0,'Reconhecer é importante, mas descrever papéis com precisão também é uma prática ética.']]},
 {title:'Missão 2 — Uso de IA',text:'Você usou IA generativa para ajudar a criar imagens e revisar código. Qual conduta é mais adequada?',choices:[['Registrar o uso e revisar criticamente o conteúdo',7,4,3,'Boa prática: transparência, revisão humana e responsabilidade pelo resultado.'],['Esconder o uso para parecer trabalho totalmente manual',-7,-3,-5,'Ocultar uma contribuição relevante pode comprometer transparência e rastreabilidade.'],['Copiar tudo sem conferir',-6,-5,-3,'O usuário continua responsável por erros, vieses e adequação do material.']]},
 {title:'Missão 3 — Fonte científica',text:'Um colega envia um gráfico de artigo e sugere colá-lo sem referência porque “ninguém vai notar”.',choices:[['Citar a fonte e verificar licença/uso',8,5,4,'Citar e respeitar condições de uso protege autoria e integridade acadêmica.'],['Usar sem citar',-10,-4,-7,'Isso pode caracterizar apropriação indevida de conteúdo.'],['Redesenhar o gráfico e omitir a fonte',-7,-2,-4,'Mudar a aparência não elimina a obrigação de atribuir a ideia ou dados de origem.']]},
 {title:'Missão 4 — Dados inesperados',text:'O resultado do experimento não confirma a hipótese do grupo. O prazo está acabando.',choices:[['Relatar o resultado real e discutir limitações',9,6,5,'Integridade científica exige preservar os dados, mesmo quando frustram expectativas.'],['Excluir os dados que atrapalham',-10,-5,-8,'Selecionar dados para forçar a conclusão compromete a validade do trabalho.'],['Alterar valores para “ajustar” a tendência',-12,-7,-10,'Fabricar ou falsificar dados é uma violação grave de integridade.']]}
];
function save(){localStorage.setItem('eticaGameState',JSON.stringify(state));}
function clamp(v){return Math.max(0,Math.min(100,v));}
function render(){scene.className='scene '+state.room; player.style.left=state.x+'%'; ['energy','knowledge','reputation','ethics'].forEach(k=>$('#'+k).textContent=state[k]); $('#objective').textContent=state.mission<missions.length?`Missão ${state.mission+1}: encontre uma situação ética e use “Interagir”.`:'Missões principais concluídas — visite a Sala dos Criadores.'; save();}
function move(dx){state.x=clamp(state.x+dx); state.energy=clamp(state.energy-.2); player.classList.add('moving'); render(); clearTimeout(move.t); move.t=setTimeout(()=>player.classList.remove('moving'),180)}
function open(html){content.innerHTML=html;modal.classList.remove('hidden')}
function close(){modal.classList.add('hidden')}
function mission(){if(state.mission>=missions.length){open(`<h2>🏆 Jornada concluída</h2><p>Você concluiu as missões centrais de integridade acadêmica.</p><button class="choice" onclick="goRoom('creators_room');document.querySelector('#modal').classList.add('hidden')">Ir para a Sala dos Criadores</button>`);return} const m=missions[state.mission]; let html=`<h2>${m.title}</h2><p>${m.text}</p><div class="choices">`; m.choices.forEach((c,i)=>html+=`<button class="choice" onclick="answer(${i})">${c[0]}</button>`); html+='</div>';open(html)}
window.answer=i=>{const m=missions[state.mission],c=m.choices[i];state.ethics=clamp(state.ethics+c[1]);state.knowledge=clamp(state.knowledge+c[2]);state.reputation=clamp(state.reputation+c[3]);state.energy=clamp(state.energy-3);state.done.push(state.mission);state.mission++;render();content.innerHTML=`<h2>Resultado</h2><p>${c[4]}</p><div class="feedback">Ética ${c[1]>=0?'+':''}${c[1]} · Conhecimento ${c[2]>=0?'+':''}${c[2]} · Reputação ${c[3]>=0?'+':''}${c[3]}</div><button class="choice" onclick="document.querySelector('#modal').classList.add('hidden')">Continuar</button>`}
window.goRoom=r=>{state.room=r;state.x=45;render()}
function map(){open(`<h2>Mapa do campus</h2><div class="mapgrid">${Object.keys(rooms).map(r=>`<button onclick="goRoom('${r}');document.querySelector('#modal').classList.add('hidden')">${labels[r]}</button>`).join('')}</div>`)}
function menu(){open(`<h2>Menu</h2><div class="choices"><button class="choice" onclick="map()">Mapa</button><button class="choice" onclick="showCredits()">Créditos</button><button class="choice" onclick="resetGame()">Reiniciar progresso</button></div>`)}
window.map=map; window.showCredits=()=>open(`<h2>Créditos e autoria</h2><p>Este jogo foi estruturado para que cada contribuição possa ser reconhecida de forma transparente.</p><div class="credits"><div class="creditCard"><b>Concepção e conteúdo acadêmico</b><br>Preencher com os responsáveis pelo conteúdo e pela proposta pedagógica.</div><div class="creditCard"><b>Programação e integração PWA</b><br>Desenvolvimento do código, lógica do jogo e integração técnica.</div><div class="creditCard"><b>Arte e assets</b><br>Registrar quem criou, selecionou, revisou ou adaptou as imagens.</div><div class="creditCard"><b>Testes, acessibilidade e revisão</b><br>Registrar estudantes e colaboradores conforme participação efetiva.</div></div><p><small>Edite este texto no arquivo app.js para inserir os nomes reais e as contribuições de cada participante.</small></p>`);
window.resetGame=()=>{localStorage.removeItem('eticaGameState');location.reload()};
$('#closeModal').onclick=close;$('#interactBtn').onclick=mission;$('#actionBtn').onclick=mission;$('#mapBtn').onclick=map;$('#menuBtn').onclick=menu;
document.querySelectorAll('[data-move]').forEach(b=>{let t;const d=b.dataset.move==='left'?-4:4; const start=e=>{e.preventDefault();move(d);t=setInterval(()=>move(d),100)}; const end=()=>clearInterval(t);b.addEventListener('pointerdown',start);b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);b.addEventListener('pointerleave',end)});
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')move(-3);if(e.key==='ArrowRight'||e.key==='d')move(3);if(e.key==='e'||e.key==='Enter')mission();if(e.key==='m')map()});
document.querySelectorAll('.portal').forEach(p=>p.onclick=()=>goRoom(p.dataset.room));
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
render();
